yelp_reviews:
  outputs:
    dev:
      dbname: yelp
      host: pg-yelp
      pass: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
